language: java
jdk:
  - oraclejdk8
script: ant build

deploy:
  provider: releases
  api_key: 
    secure: ca53f8a24d6685370200e512618f87f9593bab7f
  file: 
   - "README.md"
   - "bin/Life.jar"
  skip_cleanup: true
  on:
    tags: true
    