language: java
jdk:
  - oraclejdk8
script: ant build

deploy:
  provider: releases
  api_key: 
    secure: 06c0b8ba130b405bbb07b366c5f1bfd621ba72ce
  file: 
   - "README.md"
   - "bin/Life.jar"
  skip_cleanup: true
  on:
    tags: true
    