language: java
jdk:
  - oraclejdk8
script: ant build

deploy:
  provider: releases
  api_key: 
    secure: bc64fa3a6b3df149b5364eaae7d91ffe5e17ed23
  file: 
   - "README.md"
   - "Life.jar"
  skip_cleanup: true
  on:
    tags: true
    