language: java
jdk:
  - oraclejdk8
script: ant build

deploy:
  provider: releases
  api_key: 
    secure: 9b465f986afaa4c27c714049711a2b864d704908
  file: 
   - "README.md"
   - "bin/Life.jar"
  skip_cleanup: true
  on:
    tags: true
    